# Generated by Django 3.0.8 on 2020-07-28 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_following_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='following',
            name='followers',
        ),
        migrations.AddField(
            model_name='following',
            name='followers',
            field=models.IntegerField(default=0),
        ),
    ]
