# Generated by Django 3.0.8 on 2020-07-29 18:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_auto_20200728_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='liker',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
